app = "lifemanager-api"
primary_region = "sjc"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/api/health"
  protocol = "http"
  timeout = "2s"

[processes]
  app = "cd server && npm start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
